spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/appx-realm}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://keycloak:8080/realms/appx-realm/protocol/openid-connect/certs}
keycloak:
  realm: appx-realm
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  resource: appx-backend
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
server:
  port: 8080